KISSY.add("mods/itemview",function(e,g,l,j){function m(){m.superclass.constructor.apply(this,arguments)}var k=g.all,b=l('<li class="item"><div class="itembody vpart"><span class="icon-finish"></span><span class="text">{{value}}</span><input type="text" value=""/><span class="icon-delete"></span></div></li>');e.extend(m,j.View,{render:function(h,f,c){var a=this,h=k(b.render(h)),i;f?(k(f).attr("class","").attr("style","").addClass("item").html(h.html()),i=k(f)):i=h;a.set("el",i);c&&i.all(".itembody").style(c);
i.on("touchstart",function(d){d=d.originalEvent;if(d.touches&&d.touches.length===1){a.touchStartTimeStamp=e.now();a.touchStartPos=a.curTouchPos={x:d.pageX,y:d.pageY};a.swiping=null;a.swipflag=false;a.moveSpeedSacle=1}}).on("touchmove",function(d){var c=d.originalEvent;if(c.touches&&c.touches.length===1&&!(a.swipflag===true&&a.swiping===false)){a.swipflag=true;if(a.swiping===null){var b=c.pageX-a.touchStartPos.x,c=c.pageY-a.touchStartPos.y;if(Math.abs(b)>Math.abs(c))a.swiping=true}if(a.swiping===true){d.halt();
c=d.originalEvent;a.curTouchPos={x:c.pageX,y:c.pageY};b=c.pageX-a.touchStartPos.x;if(Math.abs(b)>40){a.moveSpeedSacle=0.3;d=((Math.abs(b)-40)*a.moveSpeedSacle+40)*(Math.abs(b)/b)}else d=b;i.all(".itembody").style("-webkit-transform","translateX("+d+"px)")}}}).on("touchend",function(d){e.log("itemview touchend start");d=d.originalEvent;if(d.touches&&d.touches.length===0){e.log("itemview touchend touches length:"+d.touches.length);e.log(a);e.log(a.swiping||"null");if(a.swiping===true){e.log("itemview touchend 1");
var c=i.all(".itembody");c.style("-webkit-transition","all 0.1s linear");c.style("-webkit-transform","translate(0px)");e.later(function(){c.style("-webkit-transition","")},210)}e.log("itemview touchend end")}});return a},destroy:function(){this.get("el").remove()}},{ATTRS:{}});return m},{requires:"node,template,mvc,anim,./itemview.css,./global.css".split(",")});
KISSY.add("mods/global",function(e,g){function l(){l.superclass.constructor.apply(this,arguments)}(function(j){function g(c,a,i,d){var b=Math.abs(c-a),e=Math.abs(i-d);return b>=e?0<c-a?"Left":"Right":0<i-d?"Up":"Down"}function k(){b.last&&Date.now()-b.last>=f&&(j(b.target).fire("longTap"),b={})}var b={},h,f=750;e.ready(function(){j(document.body).on("touchstart",function(c){var c=c.originalEvent,a=e.now(),i=a-(b.last||a);b.target="tagName"in c.touches[0].target?c.touches[0].target:c.touches[0].target.parentNode;
h&&clearTimeout(h);b.x1=c.touches[0].pageX;b.y1=c.touches[0].pageY;0<i&&250>=i&&(b.isDoubleTap=!0);b.last=a;setTimeout(k,f)}).on("touchmove",function(c){c=c.originalEvent;b.x2=c.touches[0].pageX;b.y2=c.touches[0].pageY}).on("touchend",function(){if(b.isDoubleTap)j(b.target).fire("doubleTap"),b={};else if(0<b.x2||0<b.y2){var c=30<Math.abs(b.x1-b.x2),a=30<Math.abs(b.y1-b.y2);(c||a)&&j(b.target).fire("swipe")&&j(b.target).fire("swipe"+g(b.x1,b.x2,b.y1,b.y2));b.x1=b.x2=b.y1=b.y2=b.last=0}else"last"in
b&&(h=setTimeout(function(){h=null;j(b.target).fire("tap");b={}},250))}).on("touchcancel",function(){b={}})})})(g.all);e.extend(l,e.Base,{},{cssConfig:{perspective:600,itemHeight:60,swipeThreshold:60}});return l},{requires:["node","event"]});
KISSY.add("mods/pinchitemview",function(e,g,l,j,m,k){function b(){b.superclass.constructor.apply(this,arguments)}var h=g.all,f=l('<li class="pinch-item">   <div class="pinch-wrapper">\t\t\t<div class="transform-item upper-item vpart">\t\t\t\t<span>\u53cc\u6307\u653e\u5927\u65b0\u5efa\u6761\u76ee</span>\t\t\t</div>\t\t\t<div class="transform-item bottom-item vpart">\t\t\t\t<span>\u53cc\u6307\u653e\u5927\u65b0\u5efa\u6761\u76ee</span>\t\t\t</div>       </div>\t</li>');e.extend(b,j.View,{render:function(c){var a=
h(f.render());this.get("parentNode")&&(a.appendTo(this.get("parentNode")),h(this.get("parentNode")).css("-webkit-perspective",k.cssConfig.perspective));this.set("el",a);c&&a.all(".vpart").style(c);this.set("height",0);return this},appendTo:function(c){this.get("el")?h(c).append(this.get("el")):h(c).append(this.render().get("el"));h(c).css("-webkit-perspective",k.cssConfig.perspective)},_transHeightTo:function(c){var a=this.get("el"),i=a.all(".upper-item"),d=a.all(".bottom-item"),b=this.get("defHeight"),
e;c>b?(e=0,a.height("auto").all(".pinch-wrapper").height(b).style("margin",Math.floor(c-b)/2+"px 0")):(e=Math.floor(180*(Math.acos(c/b)/Math.PI)),a.height(c).all(".pinch-wrapper").height(c).style("margin","0"),a.all(".vpart").style("opacity",1*((c+20)/80)),c=60*Math.abs(Math.cos(e*Math.PI/180))-c,d.style("bottom",-c+"px"));i.css("-webkit-transform","rotateX(-"+e+"deg)");d.css("-webkit-transform","rotateX("+e+"deg)")},destroy:function(c){function a(){var a=e.later(function(){var d=i.get("height"),
d=d-5;0>=d?(i.set("height",0),h(i.get("el")).remove(),a.cancel(),f.remove(),c&&c()):i.set("height",d)},1,!0,i)}var i=this;e.log("destroy start");var d=i.get("height"),b=i.get("defHeight"),f=i.get("el"),b=d-b;console.log("height:"+d);console.log("dh:"+b);0<b?(f.all(".pinch-wrapper").addClass("intransition"),e.later(function(){f.all(".pinch-wrapper").css("margin",0)},1,!1,i),e.later(function(){c&&c()},150,!1,i)):a();e.log("destroy end")}},{ATTRS:{height:{setter:function(c){try{this._transHeightTo(c)}catch(a){}},
value:function(){return this.get("el").css("height")}},defHeight:{value:k.cssConfig.itemHeight||60}}});return b},{requires:"node,template,mvc,anim,mods/global,./pinchitemview.css".split(",")});
KISSY.add("mods/toppinchitemview",function(e,g,l,j,m,k,b){function h(){h.superclass.constructor.apply(this,arguments);e.log("toppinchview created")}var f=g.all,c=l('<li class="pinch-item">\t\t\t<div class="transform-item  top-pinch-item vpart">\t\t\t\t<span>\u4e0b\u62c9\u65b0\u5efa\u6761\u76ee</span>\t\t\t</div>\t\t</li>');e.extend(h,k,{render:function(a,i,d){a=f(c.render());this.get("parentNode")&&(f(this.get("parentNode")).prepend(a),f(this.get("parentNode")).css("-webkit-perspective",b.cssConfig.perspective));
this.set("el",a);d&&a.all(".transform-item").style(d);return this},appendTo:function(a){this.get("el")?f(a).prepend(this.get("el")):f(a).prepend(this.render().get("el"));f(a).css("-webkit-perspective",b.cssConfig.perspective)},_transHeightTo:function(a){var c=this.get("el"),d=c.all(".transform-item"),b=this.get("defHeight"),b=180*(Math.acos(Math.min(a+3,b)/b)/Math.PI);0>b&&(b=0);e.log("rotating "+b+"deg");c.css("height",a);d.css("-webkit-transform","rotateX("+b+"deg)");d.style("opacity",1*(Math.min(a+
20,80)/80))},destroy:function(a){function c(){var b=e.later(function(){var c=d.get("height"),c=c-5;0>=c?(d.set("height",0),h.remove(),b.cancel(),a&&a()):d.set("height",c)},1,!0,d)}var d=this;e.log("destroy start");var b=d.get("height"),f=d.get("defHeight"),h=d.get("el"),g=b-f;console.log("height:"+b);console.log("dh:"+g);0<g?(h.addClass("intransition"),e.later(function(){h.height(f)},1,!1,d),e.later(function(){h.removeClass("intransition");a&&a()},150,!1,d)):c();e.log("destroy end")}},{ATTRS:{height:{setter:function(a){e.log("setting height to "+
a);this._transHeightTo(a)},value:function(){return this.get("el").css("height")}}}});return h},{requires:"node,template,mvc,anim,mods/pinchitemview,mods/global,./toppinchitemview.css".split(",")});
KISSY.add("mods/listview",function(e,g,l,j,m,k,b,h){function f(a){f.superclass.constructor.apply(this,arguments);return this}var c=g.all;l('<input type="text" value="{{value}}"/>');e.extend(f,j.View,{render:function(){var a=this;a.__setTopPinchViewHeight=e.throttle(function(c){a.topPinchViewInst||(a.topPinchViewInst=(new b).render(null,null,{"background-color":a.getColorOfIndex(0,a.get("el").all("li").length)}),a.topPinchViewInst.get("el").prependTo(a.get("el")),a._newElIndex=0);a.topPinchViewInst.set("height",
c)},50,a);c(a.get("el")).on("touchstart",function(b){console.log("touchstart");var d=b.originalEvent;a.dragging=a.dragflag=!1;d.touches&&1===d.touches.length&&(a.__dragging=!0,a.startPos1={x:d.touches[0].pageX,y:d.touches[0].pageY},a.startWinScrollTop=c(window).scrollTop());if(d.touches&&2===d.touches.length&&!a.pinchViewInst){var e=a.get("el");e.offset();var f=e.all("li").length,g=f-1,g=parseInt((d.touches[0].pageY+d.touches[1].pageY)/2/h.cssConfig.itemHeight)+1;a._newElIndex=g=g>f-1?f:g;a.__pinching=
!0;a.__dragging=!1;a.pinchViewInst=(new k).render({"background-color":"hsl("+(353+g*Math.min(70/f,10))+",95%,"+(0==g?"48%":"53%")+")"});a.pinchViewInst.get("el").insertAfter(e.all("li")[g-1]);a.startPos1={x:d.touches[0].pageX,y:d.touches[0].pageY};a.startPos2={x:d.touches[1].pageX,y:d.touches[1].pageY};a.startDistX=a.curDistX=Math.abs(a.startPos1.x-a.startPos2.x);a.startDistY=a.curDistY=Math.abs(a.startPos1.y-a.startPos2.y);a.curPos1={x:d.touches[0].pageX,y:d.touches[0].pageY};a.curPos2={x:d.touches[1].pageX,
y:d.touches[1].pageY};b.halt()}}).on("touchmove",function(b){var d=b.originalEvent;if(d.touches&&1===d.touches.length&&!0===a.__dragging){a.curWinScrollTop=c(window).scrollTop();a.curPos1={x:d.touches[0].pageX,y:d.touches[0].pageY};var f=a.curPos1.y-a.startPos1.y,h=a.curPos1.x-a.startPos1.x,g=0;0>=a.curWinScrollTop&&(g=f-(a.startWinScrollTop-a.curWinScrollTop),0<g&&(b.halt(),a.__setTopPinchViewHeight(g)),e.log("dx"+h),e.log("dy"+f),e.log("dH"+g),e.log(a.curWinScrollTop))}d.touches&&2===d.touches.length&&
(a.curPos1={x:d.touches[0].pageX,y:d.touches[0].pageY},a.curPos2={x:d.touches[1].pageX,y:d.touches[1].pageY},a.curDistX=Math.abs(a.curPos1.x-a.curPos2.x),a.curDistY=Math.abs(a.curPos1.y-a.curPos2.y),b=a.curDistY-a.startDistY,0<b&&a.pinchViewInst&&a.pinchViewInst.set("height",b))}).on("touchend",function(b){b=b.originalEvent;b.touches&&0===b.touches.length&&(a.__dragging=!1);1===b.touches.length&&(a.__pinching=!1);if(b=a.pinchViewInst||a.topPinchViewInst){var d=b.get("el");60<=b.get("height")&&(newItemEl=
(new m).render({value:"\u6211\u662f\u4e00\u4e2a\u65b0\u6761\u76ee\uff01"},d,{"background-color":a.getColorOfIndex(a._newElIndex,a.get("el").all("li").length)}).get("el"),a.editItem(newItemEl.all("span.text")));b.destroy(function(){a.refreshColor()});a.pinchViewInst=null;a.topPinchViewInst=null}});return a},add:function(a){var b=this;e.isArray(a)?e.each(a,function(a){a=(new m).render(a);c(b.get("el")).append(a.get("el"));a.set("parentNode",c(b.get("el")))}):e.isObject(a)&&(a=(new m).render(a),c(b.get("el")).append(a.get("el")),
a.set("parentNode",c(b.get("el"))));b.refreshColor()},destroy:function(){this.get("el").remove()},edit:function(a){this.editItem(a.currentTarget)},editItem:function(a){var b=c(a);c(a).parent("div.itembody").all("input").val(b.text()).show().getDOMNode().focus();var d=c(a).parent("li"),f=this.get("el").all("li");f.addClass("intransition-medium");d.removeClass("intransition-medium");e.later(function(){f.addClass("half-transparent");d.removeClass("half-transparent")},25);b.hide()},endEdit:function(a){var a=
c(a.currentTarget),b=c(a).parent("li.item").all("span.text");b.show();b.text(a.val());a.detach("blur");a.hide();this.get("el").all("li").removeClass("half-transparent")},onSwipe:function(){},refreshColor:function(){var a=this,b=a.get("el").all("li"),d=b.length;console.log(d);e.each(b,function(b,e){var f=a.getColorOfIndex(e,d);c(b).all(".vpart").style("background-color",f)})},getColorOfIndex:function(a,b){return"hsl("+(353+a*Math.min(70/b,10))+",95%,"+(0==a?"48%":"53%")+")"}},{ATTRS:{events:{value:{"span.text":{click:"edit"},
input:{blur:"endEdit"},".item":{swipe:"onSwipe"}}}}});return f},{requires:"node,template,mvc,mods/itemview,mods/pinchitemview,mods/toppinchitemview,mods/global,./listview.css".split(",")});KISSY.add("main",function(){},{requires:["mods/listview"]});KISSY.config({map:[[/(.+)-min\.(.+)?$/,"$1.$2"]],packages:[{name:"mods",tag:"20110515",path:"./",charset:"utf-8"}]});
KISSY.use("mods/listview",function(e,g){(new g({el:"#container"})).render().add([{value:"Full html5 clear demo"},{value:"drag down or"},{value:"pinch apart to add"}])});
